import Config

# Configure your database
config :eft_buddy, EftBuddy.Repo,
  username: System.get_env("DB_USERNAME"),
  password: System.get_env("DB_PASSWORD"),
  hostname: System.get_env("DB_HOSTNAME"),
  database: System.get_env("DB_NAME"),
  port: String.to_integer(System.get_env("DB_PORT")),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  # Supabase requires TLS. Options live inside `ssl:` — the separate `ssl_opts`
  # key is deprecated in Postgrex and is ignored with a warning.
  ssl: [verify: :verify_none]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :eft_buddy, EftBuddyWeb.Endpoint,
  # LOOPBACK BY DEFAULT. This used to be `{0, 0, 0, 0}` unconditionally, with a
  # `#! Change back to default before deployment !#` comment that nothing enforced.
  # Combined with `check_origin: false` and the committed `secret_key_base` below,
  # that made the dev server reachable from anywhere on the local network by anyone
  # who can read this repository — and the whole point of publishing it is that
  # everyone can.
  #
  # Set `DEV_BIND_ALL=1` when you actually want that (testing the HUD on a phone).
  # Read at compile time, which for a dev convenience is fine: `mix phx.server`
  # compiles on start, so exporting the variable and restarting is enough.
  http: [
    ip:
      if(System.get_env("DEV_BIND_ALL") in ~w(1 true),
        do: {0, 0, 0, 0},
        else: {127, 0, 0, 1}
      )
  ],
  # Phoenix's dev default. Safe now that the default bind is loopback; if you set
  # DEV_BIND_ALL you are also turning this off for the LAN, which is the reason the
  # bind is opt-in.
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  # Dev-only key, and deliberately committed — this is upstream Phoenix's own
  # generator behaviour. Production reads `secret_key_base` from the environment in
  # config/runtime.exs, which hard-raises when it is missing or blank, so this value
  # can never reach a deployed instance.
  #
  # NOT ROTATED, deliberately. Rotating a value that is committed either way
  # achieves nothing: the replacement would be equally public the moment anyone
  # clones the repository. What actually mattered was that this key was paired with
  # a server bound to every interface, and that is what changed above. The rule to
  # keep is the invariant, not the number: nothing in dev or test config may ever be
  # a value production could fall back to.
  secret_key_base: "MCvjv+WvfXN4eYNlaPdaJR2pDUyya4fofpU2kTYN+Xhq1S8r5JSWFouYjuOBwqjL",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:eft_buddy, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:eft_buddy, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :eft_buddy, EftBuddyWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/eft_buddy_web/router\.ex$",
      ~r"lib/eft_buddy_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for the dashboard
config :eft_buddy, dev_routes: true

# The session cookie is `Secure` everywhere except dev. `http:` above binds
# 0.0.0.0, and reaching the dev server on a LAN address over plain http:// is not
# a secure context, so the browser would drop a `Secure` cookie and the operator
# HUD would silently render defaults. (http://localhost is exempt from that rule;
# a LAN IP is not.) See `EftBuddyWeb.Endpoint`'s `@session_options`.
config :eft_buddy, :session_cookie_secure, false

# Do not include metadata nor timestamps in development logs
# Timestamp is wrapped in green ANSI escapes so it visually
# anchors each line. Set here (dev only) rather than in the
# base config so the production formatter stays unchanged —
# log shippers / journald / CloudWatch don't see escape codes.
config :logger, :default_formatter, format: "\e[32m[$date $time] >\e[0m [$level] $message\n"

# Enable ANSI escapes in dev so EftBuddy.Sync.Reporter.colorize_label/1
# (and anyone else gating on `IO.ANSI.enabled?/0`) actually emits colors.
# Intentionally not set in prod: log shippers / journald / CloudWatch
# render escape codes as `\e[36m…` garbage when ANSI isn't filtered.
config :elixir, :ansi_enabled, true

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
