import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :eft_buddy, EftBuddyWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
#
# `rewrite_on: [:x_forwarded_proto]` trusts the proxy/load-balancer in
# front of the app to report the original scheme.
#
# `:exclude` MUST be nested inside `:force_ssl` — it is an option of `Plug.SSL`,
# not of the endpoint. It previously sat as a sibling key here, so `Plug.SSL`
# never received it and the documented health-check exemption did nothing: a
# load-balancer probe arriving over plain HTTP got a 301 before it ever reached
# the router, making the health check permanently unusable.
#
# Both conditions are listed because `Plug.SSL`'s default is
# `[hosts: ["localhost", "127.0.0.1"]]` and passing any value replaces it
# wholesale. `paths:` is the load-bearing one: a client can spoof the `Host`
# header, so a path match is the stronger guard for the probe endpoints.
#
# EVERY probe route must be listed individually. `Plug.SSL` matches with
# `conn.path_info in paths` (deps/plug/lib/plug/ssl.ex:420) — an exact list
# comparison, NOT a prefix — so `"/health"` does not cover `"/health/sync"`. Getting
# that wrong is silent: the probe simply collects a 301 and the readiness check reads
# as permanently unhealthy. `test/eft_buddy_web/prod_config_test.exs` asserts this
# list matches the router's health routes exactly, in both directions.
#
# Note `/dev/dashboard` is deliberately NOT here: basic auth sends its password on
# every request, so it must stay HTTPS-only.
config :eft_buddy, EftBuddyWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      paths: ["/health", "/healthz", "/health/sync"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
