defmodule EftBuddyWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :eft_buddy

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # On `signing_salt`: it is NOT a secret and committing it is upstream Phoenix's
  # own generator default. The cookie's signing key is derived from
  # `secret_key_base` AND this salt; the salt is a domain separator, so knowing it
  # buys an attacker nothing without `secret_key_base` — which is supplied from the
  # environment in prod and hard-`raise`s when absent (config/runtime.exs). It is
  # read from application config rather than inlined so a deployer can rotate it
  # at build time without patching source. Do not "fix" this by reaching for
  # System.get_env/1 here: this is a module attribute, so it is evaluated at
  # COMPILE time and would bake the build machine's value into the release.
  #
  # `secure` and an explicit `max_age` are defence in depth: prod also sends HSTS
  # via force_ssl, but the flag means the cookie is never put on the wire in
  # cleartext even if something in front of the app is misconfigured. It is driven
  # from config and turned OFF in dev, because `config/dev.exs` binds 0.0.0.0 —
  # reaching the dev server on a LAN address over plain http:// is not a secure
  # context, so a `Secure` cookie would simply be dropped and the HUD would look
  # broken for no reason. (http://localhost is exempt; a LAN IP is not.)
  @session_options [
    store: :cookie,
    key: "_eft_buddy_key",
    signing_salt: Application.compile_env(:eft_buddy, :session_signing_salt, "pFyJ1+uW"),
    same_site: "Lax",
    secure: Application.compile_env(:eft_buddy, :session_cookie_secure, true),
    http_only: true,
    # 90 days. There are no accounts; this cookie only carries the per-browser
    # `operator_token`, so a long life is the desirable behaviour — it is what
    # keeps a returning visitor's server-side session addressable.
    max_age: 90 * 24 * 60 * 60
  ]

  # `max_frame_size` bounds what an unauthenticated client can push in a single
  # message, so an abusive frame is rejected before it is ever decoded.
  #
  # It is NOT the memory bound. `EftBuddy.Progress` is: it allow-lists the slice
  # keys and caps each mode slice at 128 KB, and that cap is what limits what an
  # `EftBuddy.OperatorSession` retains for up to four hours across up to 50,000
  # sessions. This number only has to sit comfortably above the largest payload the
  # server would legitimately ACCEPT.
  #
  # Which is why it is 1 MB and not 256 KB. `eft:restore` ships BOTH mode slices in
  # one frame, as JSON with the Phoenix envelope around it, while the 128 KB ceiling
  # is measured in the more compact `:erlang.external_size/1` terms. A completionist
  # operator's two slices can therefore exceed 256 KB on the wire while each is
  # comfortably inside its cap - and the failure mode was ugly: Bandit closes with
  # 1009, LiveView reconnects, the `Hud` hook re-pushes the identical frame, and the
  # page is permanently unusable with nothing in the logs to say why. A cap that can
  # reject a legitimate payload is worse than a slightly larger one. 1 MB also
  # matches `MAX_BACKUP_BYTES` in `app.js`, which bounds the same data as a file.
  @socket_options [
    connect_info: [session: @session_options],
    max_frame_size: 1024 * 1024
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: @socket_options,
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :eft_buddy,
    gzip: not code_reloading?,
    only: EftBuddyWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :eft_buddy
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # `:length` caps a request body. Plug's default is 8 MB, which is wildly more
  # than this app can ever need: it accepts exactly one small form (the bug
  # report) and has no uploads, so the only thing an 8 MB ceiling bought was a
  # cheap way for an anonymous client to tie up memory and a connection. 128 KB
  # leaves an order of magnitude of headroom over the largest legitimate POST.
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    length: 128_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug EftBuddyWeb.Router
end
